version: '3.8'

volumes:
  db:
    driver: local

services:
  db:
    # image: 172.20.1.22/proxy-cache/library/postgres:latest
    image: postgres
    restart: always
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123456aA@
      POSTGRES_DB: lake_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql