# docker-compose.yml
version: '3.3'

volumes:
  data:

services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   volumes:
  #     - data/zookeeper:/opt/zookeeper*
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092-9094:9092"
  #   environment:
  #     HOSTNAME_COMMAND: "echo $$(hostname)"
  #     BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
  #     KAFKA_ADVERTISED_HOST_NAME: 192.168.0.103
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "Topic1:3:2,Topic2:2:2"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - data/kafka:/kafka
  #   depends_on:
  #     - zookeeper
  #===========================================================================================================

  zookeeper:
    # image: confluentinc/cp-zookeeper:7.3.2
    image: 172.20.1.22/proxy-cache/confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ALLOW_ANONYMOUS_LOGIN: 1
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper:/opt/zookeeper*

  broker:
    # image: confluentinc/cp-kafka:7.3.2
    image: 172.20.1.22/proxy-cache/confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # ALLOW_PLAINTEXT_LISTENER: 1

      HOSTNAME_COMMAND: "echo $$(hostname)"
      BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.103
      KAFKA_CREATE_TOPICS: "Topic1:3:2,Topic2:2:2"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka